//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidatePrevJobsContact
    {
        public int Id { get; set; }
        public Nullable<int> Candidate { get; set; }
        public string CompanyName { get; set; }
        public string Position { get; set; }
        public Nullable<int> Contacts { get; set; }
    
        public virtual Candidate Candidate1 { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
