//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.CandidatePrevJobsContacts = new HashSet<CandidatePrevJobsContact>();
            this.CandidateSecondarySkills = new HashSet<CandidateSecondarySkill>();
            this.Events = new HashSet<Event>();
            this.GeneralInterviews = new HashSet<GeneralInterview>();
            this.TechInterviews = new HashSet<TechInterview>();
            this.Vacancies = new HashSet<Vacancy>();
        }
    
        public int Id { get; set; }
        public string FirstNameRus { get; set; }
        public string FirstNameEng { get; set; }
        public string LastNameRus { get; set; }
        public string LastNameEng { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Contacts { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> DesiredSalary { get; set; }
        public string Resume { get; set; }
        public int Status { get; set; }
        public Nullable<int> EngLevel { get; set; }
        public Nullable<System.DateTime> PSExperience { get; set; }
        public int HRM { get; set; }
        public Nullable<System.DateTime> LastContactDate { get; set; }
        public Nullable<int> LastModifier { get; set; }
        public Nullable<System.DateTime> Reminder { get; set; }
        public Nullable<bool> TechInterviewStatus { get; set; }
        public Nullable<bool> GeneralInterviewStatus { get; set; }
        public Nullable<bool> CustomerInterviewStatus { get; set; }
        public Nullable<System.DateTime> CustomerInterviewDate { get; set; }
        public Nullable<System.DateTime> CustomerInterviewEndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatePrevJobsContact> CandidatePrevJobsContacts { get; set; }
        public virtual CandidatePrimarySkill CandidatePrimarySkill { get; set; }
        public virtual CandidateStatus CandidateStatus { get; set; }
        public virtual City City1 { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual EngLevel EngLevel1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateSecondarySkill> CandidateSecondarySkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralInterview> GeneralInterviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechInterview> TechInterviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacancy> Vacancies { get; set; }
    }
}
