//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KnowBaseDBContext : DbContext
    {
        public KnowBaseDBContext()
            : base("name=KnowBaseDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CandidatePrevJobsContact> CandidatePrevJobsContacts { get; set; }
        public virtual DbSet<CandidatePrimarySkill> CandidatePrimarySkills { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<CandidateSecondarySkill> CandidateSecondarySkills { get; set; }
        public virtual DbSet<CandidateStatus> CandidateStatuses { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<EngLevel> EngLevels { get; set; }
        public virtual DbSet<EventId> EventIds { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<GeneralInterview> GeneralInterviews { get; set; }
        public virtual DbSet<GeneralSkill> GeneralSkills { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationType> NotificationTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TechInterview> TechInterviews { get; set; }
        public virtual DbSet<TechSkill> TechSkills { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vacancy> Vacancies { get; set; }
        public virtual DbSet<VacancyPrimarySkill> VacancyPrimarySkills { get; set; }
        public virtual DbSet<VacancySecondarySkill> VacancySecondarySkills { get; set; }
        public virtual DbSet<VacancyStatus> VacancyStatuses { get; set; }
    }
}
