//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public int Event1 { get; set; }
        public System.DateTime Date { get; set; }
        public int User { get; set; }
        public int EventType { get; set; }
        public string Property { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<int> Candidate { get; set; }
        public Nullable<int> Vacancy { get; set; }
        public Nullable<int> GeneralInterview { get; set; }
        public Nullable<int> TechInterview { get; set; }
    
        public virtual Candidate Candidate1 { get; set; }
        public virtual EventId EventId { get; set; }
        public virtual EventType EventType1 { get; set; }
        public virtual GeneralInterview GeneralInterview1 { get; set; }
        public virtual TechInterview TechInterview1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual Vacancy Vacancy1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
