//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechInterview : IInterview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechInterview()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public int Candidate { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int HRM { get; set; }
        public Nullable<int> Interviewer { get; set; }
        public bool Status { get; set; }
        public int TechSkill { get; set; }
        public Nullable<int> Mark { get; set; }
        public string Commentary { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Feedback { get; set; }
    
        public virtual Candidate Candidate1 { get; set; }
        public virtual City City1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual TechSkill TechSkill1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
